server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/SocialNetwork
    username: postgres
    password: bestuser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
