server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/SocialNetwork
    username: postgres
    password: bestuser
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
